/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_makeryan_modules_jnis_Mk */

#ifndef _Included_com_makeryan_modules_jnis_Mk
#define _Included_com_makeryan_modules_jnis_Mk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_makeryan_modules_jnis_Mk
 * Method:    getStaticMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_makeryan_modules_jnis_Mk_getStaticMessage
  (JNIEnv *, jclass);

/*
 * Class:     com_makeryan_modules_jnis_Mk
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_makeryan_modules_jnis_Mk_getMessage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
